name: Bug report
description: Report a problem with Patchlings
title: "[bug] "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please avoid including secrets or raw prompts.
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear and concise description of the problem.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide minimal steps and commands.
      placeholder: |
        1. pnpm demo
        2. Open http://localhost:5173
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true
  - type: input
    id: node
    attributes:
      label: Node version
      placeholder: "node -v"
  - type: input
    id: pnpm
    attributes:
      label: pnpm version
      placeholder: "pnpm -v"
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or screenshots
      description: Paste sanitized logs only.

