name: Feature request
description: Propose a new feature or improvement
title: "[feature] "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Patchlings is privacy-first. Please call out any privacy implications.
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What user pain or workflow gap does this address?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the shape of the change.
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Concrete checks that would make this done.
      placeholder: |
        - [ ] A demo run shows ...
        - [ ] Story Time includes ...
    validations:
      required: true
  - type: checkboxes
    id: privacy
    attributes:
      label: Privacy impact
      options:
        - label: This feature can be implemented without raw prompt/tool payloads
          required: false
        - label: This feature requires an explicit opt-in to reveal content
          required: false

